### ISSUE TITLE
Menu dupe issue

### ISSUE THREAD

**Issue by Kangaroux** [MarcelineVQ/AutoMarker#2]
If you right click yourself and hover over "raid target icon", it dupes the "Reset all instances" option. Every time you hover it adds a new option. Closing the menu and right clicking again clears it.

![image](https://github.com/MarcelineVQ/AutoMarker/assets/2302541/409c4b49-72f5-4e96-a710-c43d6b5ff9cb)

**Comment by MarcelineVQ** [comment]
That's odd, I can't reproduce that with vanilla unit frames or pfui. What unit frames do you use?

**Comment by Kangaroux** [comment]
> That's odd, I can't reproduce that with vanilla unit frames or pfui. What unit frames addons do you use if any?

Luna frames

**Comment by MarcelineVQ** [comment]
Confirmed it's definitely an issue with lunaframes, will have a look

**Comment by MarcelineVQ** [comment]
Sorry I don't think I can fix this from AutoMarker's end with how the luna code is written.
I'm not actually sure why luna adds this on its own at all since it's a default menu item that will show on its own just fine when the luna code for it is removed entirely.

**Comment by Kangaroux** [comment]
> Sorry I don't think I can fix this from AutoMarker's end with how the luna code is written. I'm not actually sure why luna adds this on its own at all since it's a default menu item that will show on its own just fine when the luna code for it is removed entirely.

No worries, thanks for taking a look
